
spring:
  profiles:
    active:
  mail:
    host: localhost
    port: 25
    username:
    password:
  thymeleaf:
    cache: true
server:
  servlet:
    context-path:

application:
  cors:
    allowed-origins:
    allowed-methods:
    allowed-headers:
    exposed-headers:
    allow-credentials: true
    max-age: 1800

  customerApplicationEmail: <<From email to display for customer>>
  applicationEmail: <<Email dedicated for this application>>
